// importing the mongoose package   
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

// creating a scheema for Blog Posts
const blogScheema = new Schema({
    title: {
        type: String,
        required: true
    },
    snippet: {
        type: String,
        required: true
    },
    body: {
        type: String,
        required: true
    }
}, {timestamps: true}) // the timestamps will be automatically generated by the database

// creating a constant to store models
// Name of Models usually start with a Capital Letter
const Blog = mongoose.model('blogs', blogScheema)
module.exports = Blog
